### ISSUE TITLE
Data["loctations"] on M1 OS 12.2.1 with Python 3.11

### ISSUE THREAD

**Issue by AnimoStudios** [Scarygami/location-history-json-converter#55]
Hello, 
Using the latest script and Python 3.11 on a mac and keep getting errors or empty CSV files. 

python3 location_history_json_converter.py 2020_JANUARY.json testit2.csv -f 'csvfullest' -c

Traceback (most recent call last):
  File "/Users/animo/Documents/_Code/location_history_json_converter.py", line 601, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/animo/Documents/_Code/location_history_json_converter.py", line 569, in main
    items = data["locations"]
            ~~~~^^^^^^^^^^^^^
KeyError: 'locations'

**Comment by ashwinma14** [comment]
I got the same issue - did you figure out a way to resolve it?

**Comment by AnimoStudios** [comment]
Hi, don't have a solve for the issue yet.

**Comment by rickprice** [comment]
Did you need a fix for this?

**Comment by AnimoStudios** [comment]
Hi Rick, yes looking for a fix or work around. Are you able to assist?

**Comment by edgiles** [comment]
Please see https://github.com/Scarygami/location-history-json-converter/issues/37

**Comment by rickprice** [comment]
yes, can you send me an example file that breaks, or really detailed
reproduce by instructions? ie the command line you use, since an empty CSV
file seems easy to create...

**Comment by rickprice** [comment]
I can probably turn a fix around in a day or two. I can't work on it today
anymore, but tommorrow or Monday is looking good.

**Comment by rickprice** [comment]
I just created a PR that should fix this, but its untested.

**Comment by sturmi** [comment]
> Hello, Using the latest script and Python 3.11 on a mac and keep getting errors or empty CSV files.
> 
> python3 location_history_json_converter.py 2020_JANUARY.json testit2.csv -f 'csvfullest' -c
> 
> Traceback (most recent call last): File "/Users/animo/Documents/_Code/location_history_json_converter.py", line 601, in sys.exit(main()) ^^^^^^ File "/Users/animo/Documents/_Code/location_history_json_converter.py", line 569, in main items = data["locations"] ~~~~^^^^^^^^^^^^^ KeyError: 'locations'

Hello all,
to convert the monthly files I am using this project:
[https://github.com/DovarFalcone/google-takeout-location-parser](url)
It generates one csv from all the YYYY_MONTH.json files.

regards
Thomas
